#!/usr/bin/env bash

if
  [[ -s "/home/tyson/.rvm/gems/ruby-2.5.0/environment" ]]
then
  source "/home/tyson/.rvm/gems/ruby-2.5.0/environment"
  exec thor "$@"
else
  echo "ERROR: Missing RVM environment file: '/home/tyson/.rvm/gems/ruby-2.5.0/environment'" >&2
  exit 1
fi
