#!/usr/bin/env bash

if
  [[ -s "/home/tyson/.rvm/gems/ruby-2.4.1@global/environment" ]]
then
  source "/home/tyson/.rvm/gems/ruby-2.4.1@global/environment"
  exec ri "$@"
else
  echo "ERROR: Missing RVM environment file: '/home/tyson/.rvm/gems/ruby-2.4.1@global/environment'" >&2
  exit 1
fi
