// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.first_run", false);
user_pref("app.normandy.user_id", "7f4590b8-00d1-4c55-96b6-db973973a510");
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1530289645);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1530289765);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1530289109);
user_pref("app.update.lastUpdateTime.experiments-update-timer", 1530289436);
user_pref("app.update.lastUpdateTime.recipe-client-addon-run", 1530289957);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1530289229);
user_pref("app.update.lastUpdateTime.telemetry_modules_ping", 0);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 1530289837);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.capacity", 358400);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.download.panel.shown", true);
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1530289081);
user_pref("browser.laterrun.bookkeeping.sessionCount", 4);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.migration.version", 66);
user_pref("browser.newtabpage.activity-stream.feeds.section.topstories.rec.impressions", "{\"19599\":1530289419559,\"19602\":1530289419559,\"19604\":1530289419559}");
user_pref("browser.newtabpage.activity-stream.feeds.section.topstories.spoc.impressions", "{\"211\":[1530289811004]}");
user_pref("browser.newtabpage.activity-stream.impressionId", "{e75f1e50-8d68-49e5-a397-41c4c65b4647}");
user_pref("browser.newtabpage.activity-stream.migrationLastShownDate", 1530252000);
user_pref("browser.newtabpage.activity-stream.migrationRemainingDays", 3);
user_pref("browser.newtabpage.enhanced", true);
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.onboarding.notification.last-time-of-changing-tour-sec", 0);
user_pref("browser.onboarding.notification.prompt-count", 0);
user_pref("browser.onboarding.notification.tour-ids-queue", "onboarding-tour-private-browsing,onboarding-tour-screenshots,onboarding-tour-addons,onboarding-tour-customize,onboarding-tour-default-browser,onboarding-tour-private-browsing,onboarding-tour-screenshots,onboarding-tour-addons,onboarding-tour-customize,onboarding-tour-default-browser");
user_pref("browser.onboarding.seen-tourset-version", 2);
user_pref("browser.onboarding.tour-type", "new");
user_pref("browser.pageActions.persistedActions", "{\"version\":1,\"ids\":[\"bookmark\",\"bookmarkSeparator\",\"copyURL\",\"emailLink\",\"sendToDevice\",\"pocket\",\"screenshots\"],\"idsInUrlbar\":[\"pocket\",\"bookmark\"]}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.places.smartBookmarksVersion", 8);
user_pref("browser.rights.3.shown", true);
user_pref("browser.safebrowsing.provider.google4.lastupdatetime", "1530289168334");
user_pref("browser.safebrowsing.provider.google4.nextupdatetime", "1530290955334");
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1530289102482");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1530292702482");
user_pref("browser.search.cohort", "nov17-2");
user_pref("browser.search.countryCode", "US");
user_pref("browser.search.region", "US");
user_pref("browser.sessionstore.upgradeBackup.latestBuildID", "20180607190419");
user_pref("browser.shell.mostRecentDateSetAsDefault", "1530289811");
user_pref("browser.slowStartup.averageTime", 12489);
user_pref("browser.slowStartup.samples", 4);
user_pref("browser.startup.homepage_override.buildID", "20180607190419");
user_pref("browser.startup.homepage_override.mstone", "60.0.2");
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"PersonalToolbar\":[\"personal-bookmarks\"],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"home-button\",\"customizableui-special-spring1\",\"urlbar-container\",\"customizableui-special-spring2\",\"downloads-button\",\"library-button\",\"sidebar-button\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"toolbar-menubar\":[\"menubar-items\"]},\"seen\":[\"developer-button\"],\"dirtyAreaCache\":[\"PersonalToolbar\",\"nav-bar\",\"TabsToolbar\",\"toolbar-menubar\"],\"currentVersion\":14,\"newElementCount\":2}");
user_pref("browser.urlbar.placeholderName", "Google");
user_pref("browser.urlbar.timesBeforeHidingSuggestionsHint", 0);
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1530289426291");
user_pref("devtools.onboarding.telemetry.logged", true);
user_pref("distribution.canonical.bookmarksProcessed", true);
user_pref("distribution.iniFile.exists.appversion", "60.0.2");
user_pref("distribution.iniFile.exists.value", true);
user_pref("dom.forms.autocomplete.formautofill", true);
user_pref("experiments.activeExperiment", false);
user_pref("extensions.blocklist.lastModified", "Thu, 07 Jun 2018 21:59:30 GMT");
user_pref("extensions.blocklist.pingCountVersion", -1);
user_pref("extensions.databaseSchema", 24);
user_pref("extensions.getAddons.cache.lastUpdate", 1530289645);
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.lastAppBuildId", "20180607190419");
user_pref("extensions.lastAppVersion", "60.0.2");
user_pref("extensions.lastPlatformVersion", "60.0.2");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webextensions.uuids", "{\"screenshots@mozilla.org\":\"d15ec47f-3b5c-4ad5-80fd-b509e813af17\"}");
user_pref("font.internaluseonly.changed", false);
user_pref("gecko.handlerService.migrated", true);
user_pref("media.gmp-gmpopenh264.abi", "x86_64-gcc3");
user_pref("media.gmp-gmpopenh264.lastUpdate", 1530289152);
user_pref("media.gmp-gmpopenh264.version", "1.7.1");
user_pref("media.gmp-manager.buildID", "20180607190419");
user_pref("media.gmp-manager.lastCheck", 1530289516);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("network.cookie.prefsMigrated", true);
user_pref("network.predictor.cleaned-up", true);
user_pref("pdfjs.enabledCache.initialized", true);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("pdfjs.previousHandler.preferredAction", 4);
user_pref("places.history.expiration.transient_current_max_pages", 104858);
user_pref("plugin.disable_full_page_plugin_for_types", "application/pdf");
user_pref("security.sandbox.content.tempDirSuffix", "7939c349-937b-4f00-9c15-2b64b1f69d76");
user_pref("services.blocklist.addons.checked", 1530213795);
user_pref("services.blocklist.clock_skew_seconds", 75969);
user_pref("services.blocklist.gfx.checked", 1530213795);
user_pref("services.blocklist.last_etag", "\"1528408770328\"");
user_pref("services.blocklist.last_update_seconds", 1530213795);
user_pref("services.blocklist.onecrl.checked", 1530213795);
user_pref("services.blocklist.pinning.checked", 1530213795);
user_pref("services.blocklist.plugins.checked", 1530213795);
user_pref("services.sync.engine.addresses.available", true);
user_pref("signon.importedFromSqlite", true);
user_pref("toolkit.startup.last_success", 1530289806);
user_pref("toolkit.telemetry.cachedClientID", "3718e865-6be8-4f14-90ad-f7e351931d8f");
user_pref("toolkit.telemetry.previousBuildID", "20180607190419");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
